### ISSUE TITLE
Error when changing/resetting detail sliders back to zero

### ISSUE THREAD

**Issue by wogam** [hako-mikan/sd-webui-cd-tuner#1]
Hi, thanks for making this extension. It's very good.

Error when changing/resetting detail sliders back to zero. CD will use last setting, even if you set it to 0.

> 
> *** Error running process_batch: D:\stable-diffusion-webui\extensions\sd-webui-cd-tuner\scripts\cdtuner.py0:08<00:00,  4.66it/s]
>     Traceback (most recent call last):
>       File "D:\stable-diffusion-webui\modules\scripts.py", line 490, in process_batch
>         script.process_batch(p, *script_args, **kwargs)
>       File "D:\stable-diffusion-webui\extensions\sd-webui-cd-tuner\scripts\cdtuner.py", line 110, in process_batch
>         restoremodel()
>     TypeError: restoremodel() missing 1 required positional argument: 'self'

**Comment by hako-mikan** [comment]
Thanks reporting. Fixed.

**Comment by wogam** [comment]
Works perfect now, closing issue
