### ISSUE TITLE
Unable to take effect with TensorRT.

### ISSUE THREAD

**Issue by player99963** [hako-mikan/sd-webui-cd-tuner#10]
https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT

d1,d2,con1,hd1,hd2,hrs The above items are not valid when TensorRT is enabled.
st1,st2 are not sure.
con2,bri,col1,col2,col3 are valid.

![image](https://github.com/hako-mikan/sd-webui-cd-tuner/assets/36121614/b948f1bc-98b8-43fa-8221-b935bf10a29c)

Activating unet: [TRT] cetfusion_v10
Loading TensorRT engine: D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Unet-trt\cetfusion_v10_23cd1759_cc89_sample=1x4x32x32+2x4x128x128+2x4x256x256-timesteps=1+2+2-encoder_hidden_states=1x77x768+2x77x768+2x231x768.trt
[W] 'colored' module is not installed, will not use colors when logging. To enable colors, please install the 'colored' module: python3 -m pip install colored
[I] Loading bytes from D:\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Unet-trt\cetfusion_v10_23cd1759_cc89_sample=1x4x32x32+2x4x128x128+2x4x256x256-timesteps=1+2+2-encoder_hidden_states=1x77x768+2x77x768+2x231x768.trt
Profile 0:
        sample = [(1, 4, 32, 32), (2, 4, 128, 128), (2, 4, 256, 256)]
        timesteps = [(1,), (2,), (2,)]
        encoder_hidden_states = [(1, 77, 768), (2, 77, 768), (2, 231, 768)]
        latent = [(-1946141184), (-1946140928), (-1946155776)]

CD Tuner Effective : [10, 10, 20, 0, 0, 0, 0, 0, 10, 10, 1, -1, -1, 0]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:01<00:00,  7.67it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 13.55it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:11<00:00,  2.62it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 30/30 [00:11<00:00, 12.43it/s]

**Comment by hako-mikan** [comment]
TensorRT has a unique structure, making it difficult to modify with CD-Tuner. However, by adjusting the model before converting it to TensorRT using the [Adjust feature](https://github.com/hako-mikan/sd-webui-supermerger/blob/main/README.md#adjust) of SuperMerger, you can achieve similar effects in TensorRT.
