### ISSUE TITLE
Adjustment of brightness during the generation process

### ISSUE THREAD

**Issue by zzz7xz** [hako-mikan/sd-webui-cd-tuner#12]
It would be nice if the brightness could be adjusted during (before?) the generation process.
Brightness adjustment of the supermerger is ideal, but it would require merging the models for each adjustment....

As well, if color 1, 2, 3 could be adjusted during the generation process, that would be interesting.

**Comment by hako-mikan** [comment]
It is possible, but as demonstrated with supermerger, changing colors or brightness can alter the image itself. Therefore, if the purpose is to change colors, it is more suitable to do so after generation. Another reason for not adopting this is that increasing parameters any further would cause confusion for many people, which is undesirable. Regarding color changes during generation, I believe the color map feature can achieve similar results.

**Comment by zzz7xz** [comment]
I wanted to change the image itself, since scenes like dazzling morning glow or low-light night cannot be adjusted in post-processing. As you suggested, it seems possible to do what I want with the color map. (I never thought it could be used without splitting the map.) Thank you for your advice!
