### ISSUE TITLE
The tab is missing

### ISSUE THREAD

**Issue by firefly098** [hako-mikan/sd-webui-cd-tuner#14]
The CD Tuner Tab is missing after the recent extension updates. No errors in console. Using A1111 v1.6.

**Comment by hako-mikan** [comment]
Have you installed any other extensions?

**Comment by firefly098** [comment]
Of course. I had them before too. After the update of CD Tuner extension it went missing.
![Screenshot_1](https://github.com/hako-mikan/sd-webui-cd-tuner/assets/116498783/d5880044-c0ee-4938-a0d2-17c260406a91)
![Screenshot_2](https://github.com/hako-mikan/sd-webui-cd-tuner/assets/116498783/328db867-45be-4691-9330-c6a187d2a513)

**Comment by firefly098** [comment]
I removed almost all of them. Even removed CD tuner and reinstalled it. The same thing :(

**Comment by komkom566** [comment]
@firefly098 
I had the same problem too.
It has been improved by replacing the script file with the old "ver3".

click download raw file tab
https://github.com/hako-mikan/sd-webui-cd-tuner/blob/ver3/scripts/cdtuner.py

Unfortunately, it's only a temporary measure. :-P

**Comment by hako-mikan** [comment]
Does this error still occur?
