### ISSUE TITLE
[Question] Explanation for details/hires

### ISSUE THREAD

**Issue by miasik** [hako-mikan/sd-webui-cd-tuner#20]
Could you please elaborate on adding details?
The clearest part is about the base image rendering. During this part only d1 and d2 work. Am I right?
The second part about hires.fix is unclear for me.
How Hires-Scaling option work? What parameters it takes and what it does later with them?
Do hd1 and hd2 work only during hires.fix?
What if I set hd1 and hd2 to 0 but keep Hires-Scaling turned on?
What if I turn Hires-Scaling off but put set values for hd1 and hd2?

I've read the description and made a lot of test but still confused.

**Comment by hako-mikan** [comment]
The mechanism of hr-scaling is simple: it scales the values of d1 and d2 according to the multiplier of hr. This takes precedence over the values of hd1 or hd2. Therefore, even if the values of hd1 and hd2 are 0, as long as d1 and d2 are not 0, they will be considered valid values.
