### ISSUE TITLE
Not working correctly

### ISSUE THREAD

**Issue by wogam** [hako-mikan/sd-webui-cd-tuner#4]
Hi, thanks for making this extension - it's one of the best for SD.

Currently i'm having issues, see work flow below (no errors produced)

1. Generate image with seed x, CD tuner detail set to 0  --> generates image without CD tuner
2. Generate image again with seed x, CD tuner detail set to 3 --> generates image with CD tuner
3. Generate image with seed y, CD tuner detail set to 3 --> generates image without CD tuner, even though terminal/output shows it was used
4. Generate image with seed y, CD tuner disabled --> generates same image as step 3
5. Generate image with seed y, CD tuner enabled again, detail set to 3 --> generates image with CD tuner

Every time a new seed is used, even if the detail is set 10, CD tuner isn't used unless you generate an image with CD tuner disabled and then enabled again. No errors are produced.

A1111 version: [v1.6.0] •  python: 3.10.9  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.41.2

**Comment by wogam** [comment]
Any update on this?

**Comment by wogam** [comment]
Update: this only happens with any wildcard extension enabled. With wild cards disabled it works as intended. Could this be updated to work with wildcards?

**Comment by hako-mikan** [comment]
You mean disable check box dose not work with dynamic prompt wildcards?

**Comment by wogam** [comment]
> You mean disable check box dose not work with dynamic prompt wildcards?

The extension doesn't work correctly with anyway wildcards extension installed. It only works if the wildcards extensions are disabled.

**Comment by hako-mikan** [comment]
Tell me your extension and its settings.
I couldn't reproduce it.

**Comment by wogam** [comment]
> Tell me your extension and its settings. I couldn't reproduce it.

https://github.com/adieyal/sd-dynamic-prompts

Default settings

When using a wildcards file with a LoRA for example, <LoRA1:__StrengthWildcard__>

**Comment by Heathen** [comment]
Works fine with dynamic prompts for me. But LoRa block weights break it and even without it, there are several loras that just break it and make it stop working.

**Comment by hako-mikan** [comment]
The direct cause is not yet clear, but the recent corrections might have fixed it. Please give it a try.

**Comment by wogam** [comment]
I can confirm the update has fixed the issue. Thank you so much!
