### ISSUE TITLE
When used with LoRa block weights, Changes to the values in the cd-tuner input box are not reflected

### ISSUE THREAD

**Issue by getty33** [hako-mikan/sd-webui-cd-tuner#7]
Changes to the values in the input box are not reflected. after restarting webui, the values first used for generation continue to be reflected in the generated results, taking precedence over the values in the current input box.

There is no error message, and the parameters displayed after CD Tuner Effective also reflect what was entered in the current input box. However, the generated result clearly does not.

Disabling sd-dynamic-prompts (https://github.com/adieyal/sd-dynamic-prompts) in my environment did not improve the symptoms.

A1111 version: [v1.6.0]  Python 3.10.9

**Comment by redhermes** [comment]
Can confirm. I am getting the same results/problem.

**Comment by thatjimupnorth** [comment]
Same here too. Clicking Disable doesn't actually disable either.

**Comment by redhermes** [comment]
I also had that problem (not disabling). In addition, using with image to image does not work. No API support. and the Color-Map function is unusable do to bug and UI issues. Seems like there was little to no effort made on testing. I had to uninstall due to all the bugs. Disappointing because it could be so cool.

**Comment by getty33** [comment]
After restarting webui, the display CD Tuner Effective :  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1, 0] is also output when generated with the input box in its default state.
　When run with the "disable" checkbox checked, the CD Tuner Effective display is not output, however, the generated image seems to reflect the values that were first entered after the restart.
　If the first generation is run after the restart with the disable checkbox checked, the contents of the input box are ignored. If you then uncheck the checkbox and enter some values in the input boxes, the default values (all 0s) seem to be used for the generation rather than the values in the input boxes.
　Also, what is entered in the input box is imprinted in the image metadata, even if it is not obviously reflected in the generated image.

**Comment by getty33** [comment]
Also, in my environment, these problems seemed to be caused by using LoRa block weights and CD-tuner together. CD-tuner worked fine for generation without the LoRa block weights, and CD-tuner worked fine for generation with LoRa. The reported problems seem to occur only when lora weights are specified in LoRa block weights. even if the LoRa block weights extension is installed in webui, The problem does not occur unless the lora weights are specified using the LoRa block weights extension installed on the webui.

**Comment by thatjimupnorth** [comment]
OK, cool. When will the update go live?
